name: Generate Snake
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Alokachamod
          outputs: |
            dist/github-snake.gif
      - name: Push Changes
        uses: stefanjudic/pre-commit@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          files: |
            dist/github-snake.gif
          message: "Update snake"
